        README.org --- description
        Copyright (C) 2012 Roman V. Prikhodchenko

        This file is part of encoder.

        encoder is free software: you can redistribute it and/or modify
        it under the terms of the GNU General Public License as published by
        the Free Software Foundation, either version 3 of the License, or
        (at your option) any later version.

        encoder is distributed in the hope that it will be useful,
        but WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        GNU General Public License for more details.

        You should have received a copy of the GNU General Public License
        along with encoder.  If not, see <http://www.gnu.org/licenses/>.


* Keywords:
encoder arduino microcontroller



* Description:
  

* Usage:
use it


  
* History:
Initial project version began about 2012.12(Dec).21


* Dependences:

* Encoder

#+BEGIN_SRC fundamental

	   encoderstate == FIFO (Queue)

	   00 00 00 00 start        B0000 0000=0x00
	   ab ab ab ab







	   correct
	        01 00 10 11        B0100 1011=0x4B
	    ____      _____
	   a    |____|     
	    _______      ____
         b       |____|



	   correct
	        10 00 01 11        B1000 0111=0x87
	    _______      ____
         a       |____|
	    ____      _____
	   b    |____|     


	   other incorrect or not finished:


	   not finished (for example)
	      11   10 00 01   (11)        B1110 0001=0xE1
	       _______          .......
         a__|       |_____...|
	    ________      __..........
	   b        |____|




	   incorrect (small motion)
	    xx xx  01   11        Bxxxx 0111=0x?7 (0x87 imposible ?)
	    _______      _____
	   a       |____|     
	    _______________
         b
	   



	   incorrect (small motion)
	    xx xx 10    11        Bxxxx1011=0x?B (0x4B imposible ?)
	    _______________
         a
	    _______      _____
	   b       |____|     
	   



	   incorrect (small motion)
	        10  11   01    11        B1011 0111=0xB7
	    ______________      ____
         a              |____|
	    ____      ______________
	   b    |____|     



	   incorrect (small motion)
	        01   11   10   11        B0111 1011=0x7B
	    ____      ______________
	   a    |____|     
	    ______________      ____
         b              |____|



	  --------------------------------
          01 00 10 11 0x4B                          10 00 01 11 0x87
          
	  correct numbers full turn: 0x4B 0x87
	  --------------------------------


          --------------------------------
          01 00 10 11          = 0x4B     10 00 01 11          = 0x87
             00 10 11 01       = 0x2D        00 01 11 10       = 0x1E
                10 11 01 00    = 0xB4           01 11 10 00    = 0x78
                   11 01 00 10 = 0xD2              11 10 00 01 = 0xE1             
          correct numbers half turn:
          --------------------------------


#+END_SRC fundamental
